project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: intro.qmd
        text: Project Proposal
      - href: Methodology.qmd
        text: Methodology
      - href: results.qmd
        text: Results & Discussion
      - href: lesson.qmd
        text: Lesson Learned
      - href: images/poster.jpg
        text: Poster
      - href: report.pdf
        text: Report


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

