project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: intro.qmd
        text: Introduction
      - href: dataPrep.qmd
        text: Data Preparation
      - href: Methodology.qmd
        text: Methodology
      - href: analysis.qmd
        text: Analysis
      - href: finding.qmd
        text: Results & Discussion
      - href: lesson.qmd
        text: Lesson Learned
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

