project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: intro.qmd
        text: Introduction
      - href: dataPrep.qmd
        text: Project Proposal
      - href: Methodology.qmd
        text: Methodology
      - href: analysis.qmd
        text: Analysis
      - href: finding.qmd
        text: Results & Discussion
      - href: results.qmd
        text: Lesson Learned
      - href: lesson.qmd
        text: Poster
      - href: report.qmd
        text: Report
      - href: proposal.qmd
        text: Proposal
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

