# Data Preparation

*These are the list of data our team has used for this project. Do click on the respective links to download the raw data accordingly. Additionally, xxxxx*

| File name                                  | Description                                                                                             | Source                                                                                                                                                                                                                                                                                                                             |
|--------------------------------------------|---------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Master Plan 2019 Subzone Boundary (No Sea) | Polygon layer of Singapore categorised by various sub-zones.                                            | <https://data.gov.sg/dataset/master-plan-2019-subzone-boundary-no-sea>                                                                                                                                                                                                                                                             |
| Malaysia, Singapore, and Brunei            | Vector layers from Open Street map, which were used to identify the roads and traffic of Singapore      | <https://download.geofabrik.de/asia/malaysia-singapore-brunei.html>                                                                                                                                                                                                                                                                |
| Education                                  | A csv file containing the names of schools in Singapore and their locations                             | <https://elearn.smu.edu.sg/d2l/le/content/328735/viewContent/2047886/View>                                                                                                                                                                                                                                                         |
| Primary Schools Closure and Mergers        | An article from MOE containing the annex of Primary Schools that are affected by the closure or merger. | [https://www.moe.gov.sg/-/media/files/news/press/2022/annex---names-of-schools-merging-between-2022-2025.ashx?la=en&hash=99BC8F6A971058F4AF09F1DEB1A16A1F0D9AB195](https://www.moe.gov.sg/-/media/files/news/press/2022/annex—names-of-schools-merging-between-2022-2025.ashx?la=en&hash=99BC8F6A971058F4AF09F1DEB1A16A1F0D9AB195) |
| Geographic Distribution                    | Geographic Distribution of the Population Trends.                                                       | <https://www.singstat.gov.sg/find-data/search-by-theme/population/geographic-distribution/latest-data>                                                                                                                                                                                                                             |
