---
title: "Introduction"
editor: visual
---

# Overview

## 
Theme 2: Geography of Accessibility with GIS-based Network Analysis

-   Sub-theme 1: Impact of closures or mergers of education institutions on equity of access.

For this project we will be looking at the impact of closures or mergers of education institutions on equity of access.

## The tasks

## Project Tasks\_

The project tasks are as follows:

-   to compile the necessary data

-   to derive new data sets

## The Data

The following data sets will be used:

The schools that closed down (the 4)

# Closed School

Due to low birth rate (url)

Based on the Geographic Distribution, we are able derive from ....

## These are the schools that will be closed latest  by 2025:

-   Eunos Primary School (Merge with Telok Kurau Primary School)

-   Guangyang Primary School (Townsville Primary School)

-   Pioneer Primary School (Merge with Juying Primary School but Pioneer name is retained)

-   Stamford Primary School (Farrer Park Primary School)

# Merged School

Farrer Park Primary School

Juying Primary School

Telok Kurau Primary School

Townsville Primary School
